IA-311 - Data for ERP included.
EmesaDEV/technology-radar pull request #4
Opened 2021-03-04 12:36 UTC by Nimja

2021-03-16 09:03 UTC, raduvoinea commented on data.csv
> +Kafka Desktop Consumer,Trial,Tools,FALSE,"<p><a href="https://github.com/Nimja/kafka-desktop-consumer">Github</a> Internally developed desktop consumer.</p>"
Please replace this with Kadeck the actual tool we use/recommend. :)
https://emesadev.atlassian.net/wiki/spaces/IA/pages/1937408064/KaDeck+-+Access+to+Kafka+PROD+Kafka+TEST

2021-03-16 09:05 UTC, raduvoinea requested changes
please check comment

2021-03-22 12:25 UTC, Nimja commented on data.csv
> +Kafka Desktop Consumer,Trial,Tools,FALSE,"<p><a href="https://github.com/Nimja/kafka-desktop-consumer">Github</a> Internally developed desktop consumer.</p>"
Add it yourself? ;)

The thing is, my tool is completely free, built in-house and is helpful for small testing ;)

I mean, I can remove my tool if you want.

2021-03-23 09:33 UTC, raduvoinea approved these changes

2021-03-23 09:41 UTC, merged