Reorganized some entries related to DevOps
EmesaDEV/technology-radar pull request #7
Opened 2021-03-09 10:51 UTC by pmmaga

2021-03-15 19:44 UTC, raduvoinea requested changes

2021-03-15 19:44 UTC, raduvoinea commented on data.csv
> +Elastic Search,Adopt,Platforms-and-Infra,FALSE,<p>Elastic Search is an indexing platform used by Hammer to index lots but.</p>
I like big buts :)

2021-03-15 19:44 UTC, raduvoinea commented on data.csv
> +New Relic,Adopt,Platforms-and-Infra,FALSE,<p>Monitoring tool for web and mobile applications.</p>
Isn't this more mainstream?

2021-03-15 19:44 UTC, raduvoinea commented on data.csv
> +ELK,Trial,Tools,TRUE,"<p>We are now using the ELK stack to enable advanced searching on our application logs</p>"
We're putting a lot of stuff in ELK isn't it more "Adopt" at this stage? (we kinda skipped trial on this one)

2021-03-16 17:47 UTC, pmmaga commented on data.csv
> +Elastic Search,Adopt,Platforms-and-Infra,FALSE,<p>Elastic Search is an indexing platform used by Hammer to index lots but.</p>
:D Fixed

2021-03-16 17:49 UTC, pmmaga commented on data.csv
> +New Relic,Adopt,Platforms-and-Infra,FALSE,<p>Monitoring tool for web and mobile applications.</p>
The line between mainstream and adopt isn't super clear for me. But either way, we would like to slowly abandon New Relic for newer applications as we have on prem tools that mostly accomplish the same. Up to debate.. We can make it mainstream also

2021-03-16 17:49 UTC, pmmaga commented on data.csv
> +ELK,Trial,Tools,TRUE,"<p>We are now using the ELK stack to enable advanced searching on our application logs</p>"
Yeah, fair enough. I had settled for Trial because we aren't automatically adopting it for all new projects, but we're getting there

2021-03-21 17:59 UTC, raduvoinea commented on data.csv
> +New Relic,Adopt,Platforms-and-Infra,FALSE,<p>Monitoring tool for web and mobile applications.</p>
We abandon New Relic in favour of what? Afaik we hook new apps in New Relic as well.

2021-03-21 18:00 UTC, raduvoinea approved these changes

2021-03-21 18:06 UTC, raduvoinea approved these changes

2021-03-21 18:06 UTC, merged